version: '2'
services:
  db-dev:
    build: quotes-db-mysql-docker
    image: marcal.perapoch/quotes-db-mysql-docker
    ports: ["3307:3306"]

  grafana-graphite:
    build: grafana-graphite
    image: marcal.perapoch/grafana_graphite
    ports:
      - '80:80'
      - '81:81'
      - '2003:2003'
      - '2004:2004'

  api:
    build: quotes-api
    image: marcal.perapoch/quotes-api
    ports: ["8090:8080"]
    environment:
    - QUOTES_DB_HOST=db-dev:3306
    - QUOTES_DB_NAME=quotes-db
    - QUOTES_DB_USER=quotesuser
    - QUOTES_DB_PASSWORD=quotes2016
    - GRAPHITE_URL=grafana-graphite
